services:
  crud1:
    image: crud
    build:
      context: ./crud
    container_name: crud1
    environment:
      - MYSQL_USER=${CRUD_USER}
      - MYSQL_PASSWORD=${CRUD_PASS}
      - MYSQL_DB=${CRUD_DB}
      - MYSQL_HOST=${MARIADB_SERVER}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - MYSQL_MQTT_DB=${MARIADB_DB}
      - MQTT_USR=${MQTT_USR}
      - MQTT_PASS=${MQTT_PASS}
      - PUERTO_MQTTS=${PUERTO_MQTTS}
      - DOMINIO=${DOMINIO}
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - network1

networks:
  network1:
    name: docker_iot_default
    external: true